- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
       msg: "Hello Azais!"
        
    - name: Check for current Microsoft .NET Framework version
      win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
      name: Version
      register: dotnet_version
      debug:
        msg: dotnet_version.value

